//sql file

CREATE TABLE LOGIN_INFO
( USERID VARCHAR(40) PRIMARY KEY NOT NULL,
PASSWORD_ VARCHAR(30) NOT NULL
);
CREATE TABLE STUDENT
( USERID VARCHAR2(40) NOT NULL,
S_NAME VARCHAR2(40) NOT NULL,
ROLL_NUMBER NUMBER PRIMARY KEY NOT NULL,
UG_PG VARCHAR(2) NOT NULL,
FOREIGN KEY (USERID) REFERENCES LOGIN_INFO(USERID)
);
CREATE TABLE FEES
( ROLL_NUMBER NUMBER NOT NULL,
FOREIGN KEY (ROLL_NUMBER) REFERENCES STUDENT(ROLL_NUMBER),
TUTION_FEE NUMBER NOT NULL,
HOSTEL_FEE NUMBER NOT NULL,
OTHER_CHARGES NUMBER NOT NULL,
PRIMARY KEY (ROLL_NUMBER)
);
CREATE TABLE SUBJECT
( SUBJECT_NAME VARCHAR(40) PRIMARY KEY NOT NULL,
RECORDINGS VARCHAR(100) NOT NULL,
READING_MATERIAL VARCHAR(100) NOT NULL,
CREDITS SMALLINT NOT NULL
);
CREATE TABLE EXAM
( SUBJECT VARCHAR(40) NOT NULL,
EXAM_CODE VARCHAR(6) PRIMARY KEY NOT NULL,
MARKS NUMBER NOT NULL,
EXAM_DATE DATE NOT NULL,
LENGHT VARCHAR(7) NOT NULL,
TYPE_ VARCHAR(7) NOT NULL,
FOREIGN KEY (SUBJECT) REFERENCES SUBJECT(SUBJECT_NAME)
);

CREATE TABLE COURSE
( ROLL_NUMBER NUMBER NOT NULL,
SUBJECT_NAME VARCHAR2(40) NOT NULL,
FOREIGN KEY (ROLL_NUMBER) REFERENCES STUDENT(ROLL_NUMBER),
FOREIGN KEY (SUBJECT_NAME) REFERENCES SUBJECT(SUBJECT_NAME),
PRIMARY KEY(SUBJECT_NAME,ROLL_NUMBER)
);
CREATE TABLE PROJECTS
( PROJECT_NAME VARCHAR2(40) PRIMARY KEY NOT NULL,
SUBJECT VARCHAR2(40) NOT NULL,
YEAR_ INT NOT NULL
);
CREATE TABLE MADE
( ROLL_NUMBER NUMBER NOT NULL,
PROJECT_NAME VARCHAR2(40) NOT NULL,
FOREIGN KEY (ROLL_NUMBER) REFERENCES STUDENT(ROLL_NUMBER),
FOREIGN KEY (PROJECT_NAME) REFERENCES PROJECTS(PROJECT_NAME)
);
CREATE TABLE FACULTY
( FAC_ID NUMBER PRIMARY KEY NOT NULL,
FAC_NAME VARCHAR(20) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
SUBJECT_NAME VARCHAR(40) NOT NULL,
FOREIGN KEY (SUBJECT_NAME) REFERENCES SUBJECT(SUBJECT_NAME)
);
CREATE TABLE ATTENDANCE
( ROLL_NUMBER NUMBER NOT NULL,
FAC_ID NUMBER NOT NULL,
PERCENTAGE NUMBER NOT NULL,
FOREIGN KEY (ROLL_NUMBER) REFERENCES STUDENT(ROLL_NUMBER),
FOREIGN KEY (FAC_ID) REFERENCES FACULTY(FAC_ID)
);

Insertion of Values

INSERT INTO LOGIN_INFO VALUES('singh_197110@student.nitw.ac.in',
'SINGH0123');
INSERT INTO LOGIN_INFO VALUES('bhatia_197123@student.nitw.ac.in',
'BHATIA4567');
INSERT INTO LOGIN_INFO VALUES('patel_197242@student.nitw.ac.in',
'PATEL1430');
INSERT INTO LOGIN_INFO VALUES('pradhan_196125@student.nitw.ac.in',
'PRAD43210');
INSERT INTO LOGIN_INFO VALUES('verma_196137@student.nitw.ac.in',
'ADITYA6789');
INSERT INTO LOGIN_INFO VALUES('sahani_198209@student.nitw.ac.in',
'SAHANI9876');
INSERT INTO LOGIN_INFO VALUES ('chhaje_197238@student.nitw.ac.in',
'CHHAJED7238');
INSERT INTO LOGIN_INFO VALUES ('balai_197254@student.nitw.ac.in',
'BALAI7254');
INSERT INTO LOGIN_INFO VALUES ('mishra_197258@student.nitw.ac.in',
'MISHRA7258');
INSERT INTO LOGIN_INFO VALUES ('johar_197264@student.nitw.ac.in',
'JOHAR7264');
INSERT INTO LOGIN_INFO VALUES('khan_198101@student.nitw.ac.in','KHAN8101');
